In [1]:
from scipy.stats import t
from scipy.linalg import pinvh as inv
from numpy.linalg import lstsq
import numpy.matlib as mb
import ipywidgets as widgets
import math as mt
import numpy as np
import pandas as pd
import re   

# Calibração

In [2]:
def MMQ(y, mx):
  coef = (inv(mx.T @ mx)) @ (mx.T @ y) # Faz a linearização com os dados
  return (coef)

In [3]:
def RMSE(yReal, yEstimado): # root-mean-square deviation
  residuos = np.sum(np.power((yReal - yEstimado),2))**0.5
  return(residuos)

In [4]:
def calcular_r2(y_true, y_pred):
    """
    Calcula o coeficiente de determinação R².
    
    Parâmetros:
    y_true: array-like, Valores observados (reais).
    y_pred: array-like, Valores preditos pelo modelo.
    
    Retorno:
    r2: float, Coeficiente de determinação R².
    """
    # Converter para arrays do NumPy, caso não sejam
    y_true = np.array(y_true)
    y_pred = np.array(y_pred)
    
    # Média dos valores observados
    y_mean = np.mean(y_true)
    
    # Soma dos quadrados dos resíduos (SSR)
    ss_res = np.sum((y_true - y_pred) ** 2)
    
    # Soma total dos quadrados (SST)
    ss_tot = np.sum((y_true - y_mean) ** 2)
    
    # Cálculo de R²
    r2 = 1 - (ss_res / ss_tot)
    
    return r2

## Caso 1: Sistema de 1º Ordem sendo avaliado por diversas ordens

In [5]:
x = np.matrix([10, 15, 20, 25, 30])
y = np.matrix([1, 1.5, 2.0, 2.5, 3.0])

In [6]:
tam = np.size(x.T,0) # Quantidade de valores analisados
mx = np.concatenate((x.T, np.ones((tam,1))),1)
a, b = MMQ(y.T,mx)
yEstimado = a*x+b # Y estimado
print(a, b)
print(y, '\n', yEstimado)
print(RMSE(y,yEstimado))
print(calcular_r2(y,yEstimado))

[[0.1]] [[0.]]
[[1.  1.5 2.  2.5 3. ]] 
 [[1.  1.5 2.  2.5 3. ]]
6.439293542825908e-15
1.0


In [7]:
tam = np.size(x.T,0) # Quantidade de valores analisados
mx = np.concatenate((np.power(x.T,2), x.T, np.ones((tam,1))),1)
a, b, c = MMQ(y.T,mx)
yEstimado = a*np.power(x,2)+b*x+c # Y estimado
print(a, b, c)
print(y, '\n', yEstimado)
print(RMSE(y,yEstimado))
print(calcular_r2(y,yEstimado))

[[2.22044605e-16]] [[0.1]] [[1.98951966e-13]]
[[1.  1.5 2.  2.5 3. ]] 
 [[1.  1.5 2.  2.5 3. ]]
6.110629202130578e-13
1.0


In [8]:
tam = np.size(x.T,0) # Quantidade de valores analisados
mx = np.concatenate((np.power(x.T,3), np.power(x.T,2), x.T, np.ones((tam,1))),1)
a, b, c, d = MMQ(y.T,mx)
yEstimado = a*np.power(x,3)+b*np.power(x,2)+c*x+d # Y estimado
print(a, b, c, d)
print(y, '\n', yEstimado)
print(RMSE(y,yEstimado))
print(calcular_r2(y,yEstimado))

[[-5.55111512e-16]] [[3.90798505e-14]] [[0.1]] [[5.00222086e-12]]
[[1.  1.5 2.  2.5 3. ]] 
 [[1.  1.5 2.  2.5 3. ]]
7.980840083610707e-12
1.0


## Caso 2: Sistema de 2º Ordem sendo avaliado por diversas ordens

In [9]:
x = np.matrix(np.arange(0,10,1)+np.random.uniform(0,1,10))
y = np.matrix((56*np.power(x,2)+30*x+32)+(np.random.uniform(0,1,10)))

In [10]:
tam = np.size(x.T,0) # Quantidade de valores analisados
mx = np.concatenate((x.T, np.ones((tam,1))),1)
a, b = MMQ(y.T,mx)
yEstimado = a*x+b # Y estimado
print(a, b)
print(y, '\n', yEstimado)
print(RMSE(y,yEstimado))
print(calcular_r2(y,yEstimado))

[[579.46366386]] [[-822.45715392]]
[[  48.31390349  145.28770282  515.51967406  816.93883463 1511.89262923
  2033.05943939 2933.64652266 3555.68532009 4006.18090586 5619.93203757]] 
 [[-628.90296104 -141.54416695  730.93050814 1196.20310237 2005.04149602
  2488.93600271 3196.19612882 3621.20772975 3905.87459116 4812.5145388 ]]
1384.690404781416
0.9388817655059626


In [11]:
tam = np.size(x.T,0) # Quantidade de valores analisados
mx = np.concatenate((np.power(x.T,2), x.T, np.ones((tam,1))),1)
a, b, c = MMQ(y.T,mx)
yEstimado = a*np.power(x,2)+b*x+c # Y estimado
print(a, b, c)
print(y, '\n', yEstimado)
print(RMSE(y,yEstimado))
print(calcular_r2(y,yEstimado))

[[55.99238746]] [[30.08598053]] [[32.34609551]]
[[  48.31390349  145.28770282  515.51967406  816.93883463 1511.89262923
  2033.05943939 2933.64652266 3555.68532009 4006.18090586 5619.93203757]] 
 [[  48.64265223  145.01366047  515.37848624  816.67696526 1512.30819369
  2032.78797296 2934.00416426 3555.81602718 4005.98495862 5619.84388886]]
0.8421577838020352
0.9999999773925089


In [12]:
tam = np.size(x.T,0) # Quantidade de valores analisados
mx = np.concatenate((np.power(x.T,3), np.power(x.T,2), x.T, np.ones((tam,1))),1)
a, b, c, d = MMQ(y.T,mx)
yEstimado = a*np.power(x,3)+b*np.power(x,2)+c*x+d # Y estimado
print(a, b, c, d)
print(y, '\n', yEstimado)
print(RMSE(y,yEstimado))
print(calcular_r2(y,yEstimado))

[[0.00611543]] [[55.89991782]] [[30.45526165]] [[32.06684133]]
[[  48.31390349  145.28770282  515.51967406  816.93883463 1511.89262923
  2033.05943939 2933.64652266 3555.68532009 4006.18090586 5619.93203757]] 
 [[  48.47665738  145.05057958  515.5424703   816.82050309 1512.33966952
  2032.74052449 2933.87831467 3555.68861825 4005.88462605 5620.03500644]]
0.7422349667117497
0.99999998243904


## Caso 3: Pontos de um arquivo sendo avaliado por diversas ordens

In [13]:
input = np.asmatrix(np.loadtxt('dados/dadosexp.txt', dtype='f', delimiter=','))
print(input[:,0].T,input[:,1].T)
x = input[:,0].T
y = input[:,1].T

[[ 800.9   909.2   989.15 1083.45 1195.55 1299.25 1348.6  1409.55 1493.3 ]] [[ 4.13  7.78 10.16 12.65 16.13 19.05 20.55 22.96 25.16]]


In [14]:
tam = np.size(x.T,0) # Quantidade de valores analisados
mx = np.concatenate((x.T, np.ones((tam,1))),1)
a, b = MMQ(y.T,mx)
yEstimado = a*x+b # Y estimado
print(a, b)
print(y, '\n', yEstimado)
print(RMSE(y,yEstimado))
print(calcular_r2(y,yEstimado))

[[0.03008989]] [[-19.80499247]]
[[ 4.13  7.78 10.16 12.65 16.13 19.05 20.55 22.96 25.16]] 
 [[ 4.29399943  7.55273392  9.95842082 12.79589504 16.1689744  19.2892943
  20.77422953 22.6082104  25.12823851]]
0.6117922901583114
0.9990934798974811


In [15]:
tam = np.size(x.T,0) # Quantidade de valores analisados
mx = np.concatenate((np.power(x.T,2), x.T, np.ones((tam,1))),1)
a, b, c = MMQ(y.T,mx)
yEstimado = a*np.power(x,2)+b*x+c # Y estimado
print(a, b, c)
print(y, '\n', yEstimado)
print(RMSE(y,yEstimado))
print(calcular_r2(y,yEstimado))

[[1.51579282e-05]] [[-0.00521078]] [[-9.28100936e-06]]
[[ 4.13  7.78 10.16 12.65 16.13 19.05 20.55 22.96 25.16]] 
 [[ 5.54959262  7.79257144  9.67653479 12.14771517 15.43607513 18.8172347
  20.54079022 22.7713846  26.02008075]]
1.9525722318499668
0.9907661320957912


In [16]:
tam = np.size(x.T,0) # Quantidade de valores analisados
mx = np.concatenate((np.power(x.T,3), np.power(x.T,2), x.T, np.ones((tam,1))),1)
a, b, c, d = MMQ(y.T,mx)
yEstimado = a*np.power(x,3)+b*np.power(x,2)+c*x+d # Y estimado
print(a, b, c, d)
print(y, '\n', yEstimado)
print(RMSE(y,yEstimado))
print(calcular_r2(y,yEstimado))

[[3.33800336e-09]] [[6.72008657e-06]] [[1.15577957e-08]] [[1.52574693e-11]]
[[ 4.13  7.78 10.16 12.65 16.13 19.05 20.55 22.96 25.16]] 
 [[ 6.02537988  8.06392877  9.80558969 12.13382706 15.30943974 18.6647682
  20.4091994  22.69990076 26.10091541]]
2.420669142686186
0.9858081076567031
